#!/usr/bin/env python

# Copyright 2013-2014 Massachusetts Open Cloud Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the
# License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied.  See the License for the specific language
# governing permissions and limitations under the License.

"""Create admin user with given password.

This is useful for initial setup of the HaaS, when using the 'db' auth
mechanism.
"""

from haas import model, config
import sys

config.load()
model.init_db()
db = model.Session()

if db.query(model.User).filter_by(label="admin").first() is not None:
    sys.stderr.write(
        'An admin user already exists.  Not creating new admin user.\n')
else:
    user = model.User("admin", sys.argv[1])
    db.add(user)
    db.commit()
